### ISSUE TITLE
The link to the basics tutorial isn't working

### ISSUE THREAD

**Issue by meandmytram** [MatchCake/MatchCake#41]
This link https://matchcake.github.io/MatchCake/tutorials/matchcake_basics.ipynb which is located at https://matchcake.github.io/MatchCake/readme.html in the "tutorials" section leads to 404.

**Comment by meandmytram** [comment]
The other tutorial link (iris dataset classification) yields the same error.

**Comment by JeremieGince** [comment]
Thank you to open this issue. It seems like the links work from the readme.md but not from the online documentation. I created a PR and hope it will fix this issue.
